# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4d22475a681e7a6091ac75b6ada89a8"
name = "personalize-price-app"
handle = "personalize-price-app"
application_url = "https://cigarettes-steel-innocent-bought.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sujay-development-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://cigarettes-steel-innocent-bought.trycloudflare.com/auth/callback",
  "https://cigarettes-steel-innocent-bought.trycloudflare.com/auth/shopify/callback",
  "https://cigarettes-steel-innocent-bought.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
